import csv
import math
import pathlib
from collections import defaultdict

import pandas as pd

# =============================================================
# CONFIG — update paths here if your files are elsewhere
# =============================================================

BASE_DIR = pathlib.Path(__file__).parent

PATIENT_CSV   = BASE_DIR / "data_clinical_patient_cleaned.csv"
SAMPLE_CSV    = BASE_DIR / "data_clinical_sample_cleaned.csv"
MUTATION_CSV  = BASE_DIR / "clean_mutations_master.csv"
RNA_CSV       = BASE_DIR / "cleaned_mrna_seq_v2_rsem.csv"
OUTPUT_SQL    = BASE_DIR / "insert_data.sql"

# =============================================================
# HELPERS
# =============================================================

def sql_val(v) -> str:
    """Convert a Python value to a SQL literal."""
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)):
        return str(v)
    # Escape single quotes in strings
    return "'" + str(v).replace("'", "''") + "'"


def insert(table: str, row: dict) -> str:
    """Return a single INSERT statement for the given table and row dict."""
    cols = ", ".join(row.keys())
    vals = ", ".join(sql_val(v) for v in row.values())
    return f"INSERT INTO {table} ({cols}) VALUES ({vals});"


def bool_flag(v) -> bool | None:
    """Map 'Yes'/'No'/1/0/NaN to Python bool or None."""
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return None
    if isinstance(v, (bool,)):
        return v
    if isinstance(v, (int, float)):
        return bool(int(v))
    return {"yes": True, "no": False}.get(str(v).strip().lower())


def nan_to_none(v):
    """Replace float NaN with None."""
    if isinstance(v, float) and math.isnan(v):
        return None
    return v if v != "" else None


def int_or_none(v) -> int | None:
    v = nan_to_none(v)
    return None if v is None else int(v)


def float_or_none(v) -> float | None:
    v = nan_to_none(v)
    return None if v is None else float(v)


def str_or_none(v) -> str | None:
    v = nan_to_none(v)
    return None if v is None else str(v).strip()


# =============================================================
# LOOKUP TABLE BUILDERS
# Returns (lookup_dict, list_of_insert_strings)
# lookup_dict maps the raw string value → integer PK
# =============================================================

def build_lookup(
    series: pd.Series,
    table: str,
    pk_col: str,
    val_col: str,
) -> tuple[dict, list[str]]:
    """Deduplicate a Series into a lookup table, assign integer IDs."""
    unique_vals = sorted(series.dropna().unique())
    lookup: dict[str, int] = {}
    stmts: list[str] = []
    for i, val in enumerate(unique_vals, start=1):
        lookup[val] = i
        stmts.append(insert(table, {pk_col: i, val_col: str(val)}))
    return lookup, stmts


# =============================================================
# MAIN
# =============================================================

def main() -> None:
    print("Reading source files...")
    pat  = pd.read_csv(PATIENT_CSV)
    samp = pd.read_csv(SAMPLE_CSV)
    mut  = pd.read_csv(MUTATION_CSV)
    rna  = pd.read_csv(RNA_CSV)

    lines: list[str] = []

    def section(title: str) -> None:
        lines.append("")
        lines.append(f"-- {'=' * 60}")
        lines.append(f"-- {title}")
        lines.append(f"-- {'=' * 60}")
        lines.append("")

    lines.append("-- Generated by generate_inserts.py")
    lines.append("-- Insert order respects all foreign-key constraints.")
    lines.append("")

    # ----------------------------------------------------------
    # INTEGRATED_PHENOTYPE
    # ----------------------------------------------------------
    section("INTEGRATED_PHENOTYPE")
    ip_lookup, ip_stmts = build_lookup(
        pat["integrated_phenotype"],
        "INTEGRATED_PHENOTYPE",
        "integrated_phenotype_id",
        "phenotype",
    )
    lines.extend(ip_stmts)

    # ----------------------------------------------------------
    # PATIENT
    # ----------------------------------------------------------
    section("PATIENT")
    # patient_id in the CSV is a string like '01CO001'; assign integer surrogate
    patient_id_map: dict[str, int] = {}
    for i, row in enumerate(pat.itertuples(index=False), start=1):
        patient_id_map[row.patient_id] = i
        lines.append(insert("PATIENT", {
            "patient_id": i,
            "sex":        str_or_none(row.sex),
        }))

    # ----------------------------------------------------------
    # ENCOUNTER
    # One encounter per patient in this dataset.
    # ----------------------------------------------------------
    section("ENCOUNTER")
    encounter_id_map: dict[str, int] = {}  # patient_id string → encounter_id int
    for i, row in enumerate(pat.itertuples(index=False), start=1):
        encounter_id_map[row.patient_id] = i
        ip_id = ip_lookup.get(str_or_none(row.integrated_phenotype) or "")
        lines.append(insert("ENCOUNTER", {
            "encounter_id":            i,
            "patient_id":              patient_id_map[row.patient_id],
            "integrated_phenotype_id": ip_id,
            "age":                     int_or_none(row.age),
            "os_status":               str_or_none(row.os_status),
            "os_months":               float_or_none(row.os_months),
            "dfs_status":              str_or_none(row.dfs_status),
            "dfs_months":              float_or_none(row.dfs_months),
            "cancer_stage":            str_or_none(row.stage),
            "pathology_t_stage":       str_or_none(row.pathology_t_stage),
            "pathology_n_stage":       str_or_none(row.pathology_n_stage),
            "polyps_history":          bool_flag(row.polyps_history),
            "polyps_present":          bool_flag(row.polyps_present),
            "mutation_rate":           float_or_none(row.mutation_rate),
            "mutation_phenotype":      str_or_none(row.mutation_phenotype),
            "histology":               str_or_none(row.histology),
        }))

    # ----------------------------------------------------------
    # SAMPLE LOOKUP TABLES
    # ----------------------------------------------------------
    section("PRESERVATION")
    pres_lookup, pres_stmts = build_lookup(
        samp["specimen_preservation"], "PRESERVATION",
        "preservation_id", "preservation_method")
    lines.extend(pres_stmts)

    section("MSI")
    msi_lookup, msi_stmts = build_lookup(
        samp["msi_status"], "MSI", "msi_id", "msi_status")
    lines.extend(msi_stmts)

    section("PATHOLOGY")
    path_lookup, path_stmts = build_lookup(
        samp["pathology_status"], "PATHOLOGY",
        "pathology_id", "pathology_status")
    lines.extend(path_stmts)

    section("TUMOR_SITE")
    site_lookup, site_stmts = build_lookup(
        samp["primary_site"], "TUMOR_SITE",
        "tumor_site_id", "tumor_site")
    lines.extend(site_stmts)

    section("ONCOTREE")
    onco_lookup, onco_stmts = build_lookup(
        samp["oncotree_code"], "ONCOTREE",
        "oncotree_id", "oncotree_code")
    lines.extend(onco_stmts)

    section("CANCER")
    cancer_lookup, cancer_stmts = build_lookup(
        samp["cancer_type"], "CANCER",
        "cancer_id", "cancer_type")
    lines.extend(cancer_stmts)

    section("DETAILED_CANCER")
    det_cancer_lookup, det_cancer_stmts = build_lookup(
        samp["cancer_type_detailed"], "DETAILED_CANCER",
        "detailed_cancer_id", "detailed_cancer_type")
    lines.extend(det_cancer_stmts)

    # ----------------------------------------------------------
    # SAMPLE
    # sample_id string → integer surrogate
    # ----------------------------------------------------------
    section("SAMPLE")
    sample_id_map: dict[str, int] = {}
    for i, row in enumerate(samp.itertuples(index=False), start=1):
        sample_id_map[row.sample_id] = i
        enc_id = encounter_id_map.get(row.patient_id)
        lines.append(insert("SAMPLE", {
            "sample_id":           i,
            "encounter_id":        enc_id,
            "preservation_id":     pres_lookup.get(str_or_none(row.specimen_preservation) or ""),
            "msi_id":              msi_lookup.get(str_or_none(row.msi_status) or ""),
            "pathology_id":        path_lookup.get(str_or_none(row.pathology_status) or ""),
            "tumor_site_id":       site_lookup.get(str_or_none(row.primary_site) or ""),
            "oncotree_id":         onco_lookup.get(str_or_none(row.oncotree_code) or ""),
            "cancer_id":           cancer_lookup.get(str_or_none(row.cancer_type) or ""),
            "detailed_cancer_id":  det_cancer_lookup.get(str_or_none(row.cancer_type_detailed) or ""),
            "sequenced":           bool_flag(row.sequenced),
            "copy_number":         bool_flag(row.copy_number),
            "mrna_data":           bool_flag(row.mrna_data),
            "microrna_data":       bool_flag(row.microrna_data),
            "methylation_status":  bool_flag(row.methylation_status),
            "protein_data":        bool_flag(row.protein),
            "phosphoprotein_data": bool_flag(row.phosphoprotein),
            "tmb_nonsynonymous":   float_or_none(row.tmb_nonsynonymous),
        }))

    # ----------------------------------------------------------
    # CHROMOSOME
    # ----------------------------------------------------------
    section("CHROMOSOME")
    chrom_vals = sorted(
        mut["Chromosome"].astype(str).unique(),
        key=lambda c: (0, int(c)) if c.isdigit() else (1, c),
    )
    chrom_lookup: dict[str, int] = {}
    for i, chrom in enumerate(chrom_vals, start=1):
        chrom_lookup[chrom] = i
        lines.append(insert("CHROMOSOME", {
            "chromosome_id":   i,
            "chromosome_name": chrom,
        }))

    # ----------------------------------------------------------
    # GENE  (unique genes across mutation + RNA tables)
    # ----------------------------------------------------------
    section("GENE")
    # Build a gene map from mutation file (has entrez_id + strand)
    # then supplement with any RNA-only genes
    gene_meta: dict[str, dict] = {}
    for row in mut[["Hugo_Symbol", "Entrez_Gene_Id", "Strand"]].drop_duplicates(
            subset="Hugo_Symbol").itertuples(index=False):
        gene_meta[row.Hugo_Symbol] = {
            "entrez_gene_id": int_or_none(row.Entrez_Gene_Id),
            "strand":         str_or_none(row.Strand),
        }
    for sym in rna["Hugo_Symbol"].unique():
        if sym not in gene_meta:
            # Find entrez id from RNA file if available
            sub = rna[rna["Hugo_Symbol"] == sym]["Entrez_Gene_Id"]
            entrez = int_or_none(sub.iloc[0]) if len(sub) else None
            gene_meta[sym] = {"entrez_gene_id": entrez, "strand": None}

    gene_id_map: dict[str, int] = {}
    for i, (symbol, meta) in enumerate(sorted(gene_meta.items()), start=1):
        gene_id_map[symbol] = i
        lines.append(insert("GENE", {
            "gene_id":        i,
            "hugo_symbol":    symbol,
            "entrez_gene_id": meta["entrez_gene_id"],
            "strand":         meta["strand"],
            "gene_type":      None,
            "annotation":     None,
        }))

    # ----------------------------------------------------------
    # MUTATION  (one row per unique mutation_id)
    # ----------------------------------------------------------
    section("MUTATION")
    mut_deduped = mut.drop_duplicates(subset="mutation_id")
    mutation_id_map: dict[str, int] = {}
    for i, row in enumerate(mut_deduped.itertuples(index=False), start=1):
        mutation_id_map[row.mutation_id] = i
        lines.append(insert("MUTATION", {
            "mutation_id":            i,
            "chromosome_id":          chrom_lookup.get(str(row.Chromosome)),
            "start_position":         int_or_none(row.Start_Position),
            "end_position":           int_or_none(row.End_Position),
            "consequence":            str_or_none(row.Consequence),
            "variant_classification": str_or_none(row.Variant_Classification),
            "variant_type":           str_or_none(row.Variant_Type),
            "reference_allele":       str_or_none(row.Reference_Allele),
            "tumor_seq_allele1":      str_or_none(row.Tumor_Seq_Allele1),
            "tumor_seq_allele2":      str_or_none(row.Tumor_Seq_Allele2),
            "hgvsc":                  str_or_none(row.HGVSc),
            "hgvsp":                  str_or_none(row.HGVSp),
            "transcript_id":          str_or_none(row.Transcript_ID),
            "validation_status":      str_or_none(row.Validation_Status),
            "sequencing_phase":       str_or_none(row.Sequencing_Phase),
        }))

    # ----------------------------------------------------------
    # MUTATION_GENE  (bridge: each mutation → one gene in this dataset)
    # ----------------------------------------------------------
    section("MUTATION_GENE")
    seen_mg: set[tuple[int, int]] = set()
    for row in mut_deduped[["mutation_id", "Hugo_Symbol"]].itertuples(index=False):
        mid = mutation_id_map.get(row.mutation_id)
        gid = gene_id_map.get(row.Hugo_Symbol)
        if mid and gid and (mid, gid) not in seen_mg:
            seen_mg.add((mid, gid))
            lines.append(insert("MUTATION_GENE", {
                "mutation_id": mid,
                "gene_id":     gid,
            }))

    # ----------------------------------------------------------
    # SAMPLE_MUTATION  (bridge: all rows, capturing per-sample counts)
    # ----------------------------------------------------------
    section("SAMPLE_MUTATION")
    seen_sm: set[tuple[int, int]] = set()
    for row in mut.itertuples(index=False):
        sid = sample_id_map.get(row.sample_id)
        mid = mutation_id_map.get(row.mutation_id)
        if sid is None or mid is None:
            continue
        key = (sid, mid)
        if key in seen_sm:
            continue
        seen_sm.add(key)
        lines.append(insert("SAMPLE_MUTATION", {
            "sample_id":       sid,
            "mutation_id":     mid,
            "t_ref_count":     int_or_none(row.t_ref_count),
            "t_alt_count":     int_or_none(row.t_alt_count),
            "n_ref_count":     int_or_none(row.n_ref_count),
            "n_alt_count":     int_or_none(row.n_alt_count),
            "mutation_status": str_or_none(row.Mutation_Status),
        }))

    # ----------------------------------------------------------
    # RNA_EXPRESSION
    # Source is wide-format: rows = genes, columns = sample IDs.
    # Melt to long format for normalised INSERT rows.
    # ----------------------------------------------------------
    section("RNA_EXPRESSION")
    sample_cols = [c for c in rna.columns if c not in ("Hugo_Symbol", "Entrez_Gene_Id")]
    # Use positional column indices to avoid itertuples mangling column names
    # that start with digits (e.g. '01CO001' becomes inaccessible via attribute).
    symbol_col_idx = rna.columns.get_loc("Hugo_Symbol")
    sample_col_indices = [(col, rna.columns.get_loc(col)) for col in sample_cols]
    rna_values = rna.values  # numpy array for fast row access
    expr_id = 1
    for row_arr in rna_values:
        symbol = row_arr[symbol_col_idx]
        gid = gene_id_map.get(symbol)
        if gid is None:
            continue
        for col, col_idx in sample_col_indices:
            sid = sample_id_map.get(col)
            if sid is None:
                continue
            val = row_arr[col_idx]
            expr_val = float_or_none(val)
            lines.append(insert("RNA_EXPRESSION", {
                "expression_id":    expr_id,
                "sample_id":        sid,
                "gene_id":          gid,
                "expression_value": expr_val,
            }))
            expr_id += 1

    # ----------------------------------------------------------
    # WRITE OUTPUT
    # ----------------------------------------------------------
    print(f"Writing {len(lines):,} lines to {OUTPUT_SQL} ...")
    OUTPUT_SQL.write_text("\n".join(lines), encoding="utf-8")
    print("Done.")
    print(f"\nSummary:")
    print(f"  PATIENT rows:        {len(pat)}")
    print(f"  ENCOUNTER rows:      {len(pat)}")
    print(f"  SAMPLE rows:         {len(samp)}")
    print(f"  GENE rows:           {len(gene_id_map)}")
    print(f"  CHROMOSOME rows:     {len(chrom_lookup)}")
    print(f"  MUTATION rows:       {len(mutation_id_map)}")
    print(f"  MUTATION_GENE rows:  {len(seen_mg)}")
    print(f"  SAMPLE_MUTATION rows:{len(seen_sm)}")
    print(f"  RNA_EXPRESSION rows: {expr_id - 1:,}")


if __name__ == "__main__":
    main()
